# 应用服务 WEB 访问端口
server:
  port: 8080

minio:
  endpoint: http://120.27.236.84:9000
  username: minioadmin
  password: minioadmin
  defaultBucket: bucket
  presignedUrlExpiry: 7

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

